version: "3.1"
services:
  web:
    image: odoo:13.0
    volumes:
      - ./config:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
      - data:/var/lib/odoo
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data
  nginx:
    image: nginx
    volumes:
      - ./sites-available:/etc/nginx/conf.d
    ports:
      - "80:80"
volumes:
  data:
  db:
