version: "3.1"
services:
  web:
    image: odoo:13.0
    volumes:
      - ./config:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
      - data:/var/lib/odoo
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/psql-pass
      - POSTGRES_USER=odoo
      - PGDATA=db
    secrets:
      - psql-pass
    volumes:
      - db:/var/lib/postgresql/data
  nginx:
    image: nginx
    volumes:
      - ./sites-available:/etc/nginx/conf.d
    ports:
      - "80:80"
secrets:
  psql-pass:
      external: true
volumes:
  data:
  db:
