version: '2'
services:
  web:
    image: odoo:13.0
    container_name: odoo
    restart: always
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./config:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
  db:
    image: postgres:10
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    network_mode: host
    volumes:
      - ./sites-available:/etc/nginx/conf.d
    ports:
      - "80:80"

